version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Echo versions
          command: |
            node --version
            yarn --version
      - run:
          name: set GIT name and email
          command: |
            git config --global -l
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global -l
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - strapi-molecules-v1-{{ checksum "yarn.lock" }}
            - strapi-molecules-
      - run:
          name: Install
          command: |
            yarn bootstrap
      - save_cache:
          paths:
            - ./node_modules
          key: strapi-molecules-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: |
            yarn test
      - codecov/upload:
          flags: unittest
          file:
      - run:
          name: Bump version
          command: |
            yarn version-only
workflows:
  version: 2
    build-and-test:
      jobs:
          - build-and-test:
            filters:
              branches:
                only:
                  - master
